services:
  catalogdb:
    container_name: catalogdb
    image: postgres
    environment:
      - POSTGRES_USER=postgresDocker
      - POSTGRES_PASSWORD=postgresDocker
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
        - "2345:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/ 